### ISSUE TITLE
Es wird zu teuer

### ISSUE THREAD

**Issue by JustusAdam** [kiliankoe/github-shop-bestellung#16]
Es hat sich herausgestellt, das wir nicht um die Einfuhrsteuer herumkommen. Darüber hinaus skaliert der Versand mit dem Warenwert mit.

Die sich daraus ergebende Preistabelle (kosten \* ca 1.58 : + 0.19 für Steuer, ca +0.39 für Versand) sieht wie folgt aus:

Invertocat Hoodie: 86.9€
Black GitHub mug: 18.96€
Arctocat: 39.5€
Invertocat 2.0: 39.5€
Atom and electron Sticker: 7.9€
Piratocat: 39.5€
Die Cut Sticker: 1.58€
Sticker Pack 3: 7.9€
Atom Coasters: 7.9€
Octicons Shirt: 39.5€

Kilian: 92.0€ -> 145.36€
Steiger: 25.0€ -> 39.5€
Justus: 30.0€ -> 47.400000000000006€
Hoodie: 26.0€ -> 41.08€
Felix D.: 12.0€ -> 18.96€
Felix W: 72.0€ -> 113.76€
Sascha: 50.0€ -> 79.0€
Stephan: 17.0€ -> 26.86€
Philipp: 5.0€ -> 7.9€
Lucas V: 25.0€ -> 39.5€
Laen: 55.0€ -> 86.9€
Ollie: 5.0€ -> 7.9€

Da das sehr viel Geld ist werden wir das mit der Bestellung wohl erst mal lassen.

**Comment by hoodie** [comment]
naja, obwohl es ist ja bald Weihnachten :S

**Comment by JustusAdam** [comment]
Es gab separate Bestellungen
