### ISSUE TITLE
Free Shipping, heute

### ISSUE THREAD

**Issue by JustusAdam** [kiliankoe/github-shop-bestellung#17]
Vor 14 Stunden kam ein Tweet von GitHub, dass es heute keine Kosten für das shipping gibt, und das scheint für international zu gelten.

Wer also sein Zeug gerne hätte sollte es innerhalb der nächsten 9 stunden selbst bestellen.

MfG Justus

@Feliix42 @h4llow3En @tocsinDE @phipse @lucasvog @LarsEngeln @olivergierke @steigr

**Comment by odrotbohm** [comment]
Komplett bestellen ist keine Option? IIRC waren doch nur die hohen Versandkosten das Problem?

**Comment by JustusAdam** [comment]
Wir müssten die wegen Zoll eh in kleinere aufteilen. Wir wollten die große ja nur machen, weil wir dachten dass das Versandkosten spart.
Da Versandkosten jetzt kein Thema mehr sind sind große Bestellungen wegen des Zolls eher hinderlich statt vorteilhaft.

**Comment by Feliix42** [comment]
Also bei mir wird der Versand irgendwie berechnet. Keine Ahnung, kann auch mein Fehler sein (zu geringer Bestellwert?).

**Comment by JustusAdam** [comment]
Bei mir gehts immer noch

<img width="673" alt="screen shot 2015-12-01 at 11 36 32" src="https://cloud.githubusercontent.com/assets/5824532/11498462/dd106d42-981f-11e5-81b3-db44c65a15a4.png">

**Comment by phipse** [comment]
Bei mir gibts auch kein "Free shipping". Weder für 5$ noch für 30$ Bestellwert gibts diese Option.

**Comment by JustusAdam** [comment]
Ich habe getestet, minimal Bestellwert 30$. Ab 30$ gibts free shipping.

**Comment by odrotbohm** [comment]
Mittlerweile ist auch in SFO Dienstag?

**Comment by phipse** [comment]
Ah, ich hab geschielt. 30$ war das shipping, 21$ der Bestellwert. Also müssen wir auf 30$+ kommen. Kann wer meine Atom-Coasters mitbestellen für 5$?
